package statementInterEnum;

public enum EoneLineStatementType {
    INT_ASSIGN, STRING_ASSIGN, BOOL_ASSIGN, ARR_INT_ASSIGN, ARR_BOOL_ASSIGN, INT_DECLARATION, BOOL_DECLARATION, STRING_DECLARATION, ARR_INT_DECLARATION, ARR_BOOL_DECLARATION,
    CONST_INT_DECLARATION, CONST_BOOL_DECLARATION, CONST_STRING_DECLARATION
}