package statementInterEnum;

public enum EoneLineStatementType {
    INT_ASSIGN, STRING_ASSIGN, BOOL_ASSIGN, ARR_INT_ASSIGN, ARR_BOOL_ASSIGN, INT_DECLARATION, BOOL_DECLARATION, STRING_DECLARATION, ARR_INT_DECLARATION, ARR_BOOL_DECLARATION,
    CONST_INT_DECLARATION, CONST_BOOL_DECLARATION, CONST_STRING_DECLARATION, PROCEDURE_CALL, UNKNOWN_ASSIGN, UNKNOWN_ARR_ASSIGN, TERNAR_ASSIGN, INT_TERNAR_DECLARATION, STRING_TERNAR_DECLARATION, BOOL_TERNAR_DECLARATION
}